# Generated by Django 3.2.9 on 2021-11-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0002_rename_movies_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('firstname',),
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(to='pinterest.Category'),
        ),
        migrations.AddField(
            model_name='series',
            name='categories',
            field=models.ManyToManyField(to='pinterest.Category'),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(to='pinterest.Cast'),
        ),
        migrations.AddField(
            model_name='series',
            name='cast',
            field=models.ManyToManyField(to='pinterest.Cast'),
        ),
    ]
